Lazy load top 200 cryptos
Urala-Communications/the-markets pull request #51
Opened 2022-03-17 03:27 UTC by lampvux

add infinite load top 200 cryptos symbols

2022-03-17 07:12 UTC, pixelomo requested changes
The infinite loader works nicely however I notice that the prices are being fetched for all coins. For example DAI previously showed price.

The logo fetch logic looks good but I don't see it working, fetching logos and generating a cryptologos.scss

Many of the new coins (51-200) have errors when viewing their item page, finage data fetches fail, the price is $0 or the page doesn't load at all for example /cryptocurrency/huobi-btc
_(This can be split into a new ticket we can resolve after this branch is merged)_

2022-03-17 07:12 UTC, pixelomo commented on frontend/modules/cryptologocheck.js
> +async function getSingleCoin(symbol){
this looks good however I'm not seeing missing logos being fetched or the cryptologo.scss being created when running locally

2022-03-18 04:14 UTC, lampvux commented on frontend/components/IndexList.vue
> +        <div class="icon" :class="index.icon ? index.icon : 's-' + index.symbol.toLowerCase()" :id="index.symbol.toUpperCase()"   />
fix icon logo not load in homepage

2022-03-18 04:15 UTC, lampvux commented on frontend/pages/cryptocurrency/index.vue
> +            // fetch crypto pricing on load
fetch crypto price on load

2022-03-18 07:22 UTC, merged